### PR TITLE
OSEP #1

### PR DESCRIPTION
**Pull request by jamesturk**
Fixes openstates/issues#277

https://github.com/openstates/enhancement-proposals/blob/approve-osep-1/final/001-purpose-and-process.md

### CODE REVIEW

**Comment by jamesturk** [comment]
Feedback greatly appreciated, hope is to have the conversations about everything from municipal data to data schema improvements in this format.  Once approved I'll go about converting the myriad of stray enhancement proposals sitting in openstates/issues and discussions to drafts.

**Review by jessemortenson — APPROVED** [review]
Yeah, I think it's beneficial to have some official way to propose bigger changes to one or more Open States applications/services. 

At Civic Eagle we use a process like this internally. Main difference with our template is we also have prompts for drawbacks, alternatives, and for unresolved questions. Might be nice to add one of those (or a combination of them) to prompt thought about what else was considered / tradeoffs.

**Comment by jamesturk** [comment]
👍 thanks, going to broaden the backwards compatibility section to drawbacks.  Open to adding alternatives & unresolved questions if they aren't getting addressed in rationale, but hoping we can keep it simple for now.

**Review by showerst — APPROVED** [review]

**Review by csnardi — APPROVED** [review]
Looks good to me! As Jesse mentioned, this should be super helpful for any future major changes.

**Pull request merged**
